apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: translation-notarization
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYjovL21vbmdvZGIudHJhbnNsYXRpb24tbm90YXJpemF0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L3RyYW5zbGF0aW9uLW5vdGFyaXphdGlvbg==
  REDIS_URL: cmVkaXM6Ly9yZWRpcy50cmFuc2xhdGlvbi1ub3Rhcml6YXRpb24uc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OQ==
  MINIO_ENDPOINT: bWluaW8udHJhbnNsYXRpb24tbm90YXJpemF0aW9uLnN2Yy5jbHVzdGVyLmxvY2Fs
  MINIO_PORT: OTAwMA==
  MINIO_USE_SSL: ZmFsc2U=
  MINIO_ACCESS_KEY: YWRtaW4=
  MINIO_SECRET_KEY: cGFzc3dvcmQxMjM=
  MINIO_BUCKET: ZG9jdW1lbnRz
  JWT_SECRET: c3VwZXJzZWNyZXRqd3Q=
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVRDVzFwSElIZkMwU2FTNE90clJIZHZLVkNnRFpEZlZjWkJEcGp6cjNUcUtHWTNFczVkd0pHcmVzTlBJUTliOGdxUUlTbTdydml4Z2owRDFMYllaVUZEaDAwSTF3TFYzclY=
  STRIPE_PUBLISHABLE_KEY: cGtfdGVzdF81MVRDVzFwSElIZkMwU2FTNFZMWUpvM0tvNkVMNmNJVU9oR3MyRkJpR1ZhdHhtNkZhR29EMFZHWUVBTWk1aThDb2tzSXNldU5KM3B2dU0yclh2UnVVUVQxWDAwQTBqazBTeTU=
  STRIPE_WEBHOOK_SECRET: d2hzZWNfMDRhMDljYmU2Yjg3MzRmMGY5NTJmNTBkZmFhNTMyNDIxYTJkNjk2ZGRhODVhOTQ2ZGI0MzI1YzlhZGIxZTk2MA==
  FRONTEND_URL: aHR0cDovL2xvY2FsaG9zdDozMDAw
